local builtin = require('telescope.builtin')
vim.keymap.set('n', '<C-P>', builtin.find_files, { silent = true })
vim.keymap.set('n', '<leader>ft', builtin.git_files, { silent = true })
vim.keymap.set('n', '<leader>fg', builtin.live_grep, { silent = true })
vim.keymap.set('n', '<leader>fb', builtin.buffers, { silent = true })
vim.keymap.set('n', '<leader>fs', builtin.git_status, { silent = true })
