vim.o.autoindent = true
vim.o.compatible = false
vim.o.cursorline = true
vim.o.expandtab = true
vim.o.hlsearch = true
vim.o.ignorecase = true
vim.o.incsearch = true
vim.o.mouse = 'a'
vim.o.number = true
vim.o.relativenumber = true
vim.o.shiftwidth = 4
vim.o.showmatch = true
vim.o.softtabstop = 4
vim.o.swapfile = false
vim.o.syntax = true
vim.o.tabstop = 4
vim.o.termguicolors = true

vim.g.mapleader = ' '
